config/routes.rb
Rails.application.routes.draw do

  get 'documents/show'
  get 'projects/index' => 'projects#index', as: :projects_index
  
  resources :projects

  devise_for :admins, 
  controllers: {sessions: "admins/sessions"}

  # Routes for devise admin
  devise_scope :admin do
    get '/login' => 'admins/sessions#new', as: :login
  end

  # Routes for admin-projects       
  authenticated :admin do
    get '/admin/index' => 'admin#index', as: :admin_index
    get '/admin' => 'admin#index', as: :admin_root
    #Route for generate PDF
    get ':id/document.pdf' => 'documents#show', as: 'generate_pdf'
    # Route for update departament field
    get 'update_departaments' => 'projects#update_departaments', as: 'update_departaments'
    root 'admin#index'
  end


  root 'home#index'
  #root 'projects#index'

 
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admin/index.html.erb
<script type="text/javascript">
  $(function(){
    $(document).ready(function(){
      document.addEventListener("turbolinks:before-cache", function() {
      dataTable.destroy();
    });
    var dataTable = $("#myTable").DataTable({
      columns: [
        { searchable: false},
        { searchable: false},
        null,
        { searchable: false},
        { searchable: false},
        { searchable: false}
      ]
    });
    });
  })
</script>
<div class="wrapper-all-project">
        <div class="project-list">
          <table id="myTable">
            <thead>
              <tr>
                <th>
                  Coordenador
                </th>
                <th>
                  Título
                </th>
                <th> 
                  Área de estudo
                </th>
                <th>
                  Recursos Concedidos
                </th>
                
                <th>
                  Edição
                </th>
                <th>
                  Apagar
                </th>
              </tr>
            </thead>
            <tbody>
              <% @projects.each do |project| %>
                <tr>
                  <td><%= project.coordinator_name %></td>
                  <td><%= link_to project.title, project_path(project) %></td>
                  <td><%= project.subject_area%></td>   
                  <td><%= number_to_currency(project.money_approved, unit: 'R$', delimiter: '.', separator: ',') %></td>
                  <td><%= link_to 'Editar', edit_project_path(project) %></td> 
                  <td><%= link_to 'Apagar Projeto', project_path(project), method: :delete, data: {confirm: 'Tem certeza que deseja apagar o projeto?'} %></td>     
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <p class="text-center">
          <%= link_to 'Cadastrar novo projeto', new_project_path, class: 'btn btn-secondary' %>
          <%= link_to 'logout', destroy_admin_session_path, method: :delete, class: 'btn btn-secondary' %>
        </p>
        
</div>