config/routes.rb
Rails.application.routes.draw do

  get 'documents/show'
  get 'projects/index' => 'projects#index', as: :projects_index
  
  resources :projects

  devise_for :admins, 
  controllers: {sessions: "admins/sessions"}

  # Routes for devise admin
  devise_scope :admin do
    get '/login' => 'admins/sessions#new', as: :login
  end

  # Routes for admin-projects       
  authenticated :admin do
    get '/admin/index' => 'admin#index', as: :admin_index
    get '/admin' => 'admin#index', as: :admin_root
    #Route for generate PDF
    get ':id/document.pdf' => 'documents#show', as: 'generate_pdf'
    # Route for update departament field
    get 'update_departaments' => 'projects#update_departaments', as: 'update_departaments'
    root 'admin#index'
  end


  root 'home#index'
  #root 'projects#index'

 
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'site'
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div>
  <p class="text-center">
    Bem-vindo ao <b>Sistema de Transparência de Projetos</b>
  </p>
  <div class="col-md-12">
    <p class="text-justify">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque bibendum placerat ligula eget malesuada. Mauris non nibh et ipsum fermentum tempor nec eu arcu. Nunc at libero efficitur urna egestas rhoncus sit amet a ipsum. Aenean tristique nunc vitae mi egestas molestie. Phasellus vel porttitor dui. In sit amet lorem nibh. Sed pellentesque mattis sem ut fermentum. Suspendisse congue elementum augue, et sollicitudin metus semper pharetra. Etiam porta ornare tincidunt. Pellentesque porttitor, tortor vel consectetur placerat, ligula urna hendrerit magna, interdum dictum arcu enim ac augue. Integer condimentum nisl at varius ultrices. Nulla facilisi.
    </p>
    <p class="text-center">
      <%= link_to "Ver Projetos", projects_index_path, class: 'btn btn-secondary'%>
      <%= link_to "Métricas", root_path, class: 'btn btn-secondary'%>
      <%= link_to "Login", new_admin_session_path, class: 'btn btn-secondary'%>

    </p>
  </div> 
</div>