config/routes.rb
Rails.application.routes.draw do

  get 'documents/show'
  get 'projects/index' => 'projects#index', as: :projects_index
  
  resources :projects

  devise_for :admins, 
  controllers: {sessions: "admins/sessions"}

  # Routes for devise admin
  devise_scope :admin do
    get '/login' => 'admins/sessions#new', as: :login
  end

  # Routes for admin-projects       
  authenticated :admin do
    get '/admin/index' => 'admin#index', as: :admin_index
    get '/admin' => 'admin#index', as: :admin_root
    #Route for generate PDF
    get ':id/document.pdf' => 'documents#show', as: 'generate_pdf'
    # Route for update departament field
    get 'update_departaments' => 'projects#update_departaments', as: 'update_departaments'
    root 'admin#index'
  end


  root 'home#index'
  #root 'projects#index'

 
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  has_one :coordinator, foreign_key: 'Ori_Nome',
  						primary_key: 'coordinator_name'
  validates :coordinator_name, :title, :subject_area, :academic_unit, :departament, :abstract, :keyword1, :keyword2, :keyword3, :keyword4, :start_date, :end_date, :money_approved, :pocket, presence: true

  serialize :pocket, Array
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  layout 'site'
  before_action :find_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, except: [:index, :show]

  def index
    @projects = Project.all
  end

  def show
  end

  def new
    @coordinators = Coordinator.all.first.Ori_Nome
    @project = Project.new
    @departaments = Departament.where("Dep_Local = ?", Place.first.Loc_Cod)
    @places = Place.all
    @areas = Area.all
    @options =[]
  end

  def create
    #@project = Project.new(project_params)
    
    coordinator_name = project_params[:coordinator_name]
    title = project_params[:title]
    subject_area = project_params[:subject_area]
    academic_unit = project_params[:academic_unit]
    departament = project_params[:departament]
    abstract = project_params[:abstract]
    keyword1 = project_params[:keyword1]
    keyword2 = project_params[:keyword2]
    keyword3 = project_params[:keyword3]
    keyword4 = project_params[:keyword4]
    start_date = project_params[:start_date]
    end_date = project_params[:end_date]
    financing = project_params[:financing]
    financing_is_public = project_params[:financing_is_public]
    financing_is_nacional = project_params[:financing_is_nacional]
    money_approved = project_params[:money_approved]
    organization = project_params[:organization]
    
    pocketAjeitando = project_params[:pocket].split(';')

    pocket = Array.new(project_params[:numberOfYears].to_i)
    for i in 1..project_params[:numberOfYears].to_i
      pocket[i-1] = pocketAjeitando[i-1].to_f 
    end
  
    @project = Project.new(coordinator_name: coordinator_name, title: title, subject_area: subject_area, academic_unit: academic_unit, departament: departament, abstract: abstract, keyword1: keyword1, keyword2: keyword2, keyword3: keyword3, keyword4: keyword4, start_date: start_date, end_date: end_date, financing: financing, financing_is_public: financing_is_public, financing_is_nacional: financing_is_nacional, money_approved: money_approved, pocket: pocket, organization: organization)

    if @project.save
      redirect_to project_path(@project), notice: 'Projeto cadastrado com sucesso.'
    else
      puts @project.errors.full_messages
      redirect_to new_project_path, notice: @project.errors.full_messages
    end
  end


  def edit
    @departaments = Departament.where("Dep_Local = ?", @project.academic_unit)#Place.first.Loc_Cod)
    @places = Place.all
    @areas = Area.all

    # Como tem o jquery para a formatação do dinheiro, fiz essa gambiarra para não perder uma casa decimal
    if @project.money_approved.round(1) == @project.money_approved
      @project.money_approved = @project.money_approved * 10
    end 
  end

  def update

    coordinator_name = project_params[:coordinator_name]
    title = project_params[:title]
    subject_area = project_params[:subject_area]
    academic_unit = project_params[:academic_unit]
    departament = project_params[:departament]
    abstract = project_params[:abstract]
    keyword1 = project_params[:keyword1]
    keyword2 = project_params[:keyword2]
    keyword3 = project_params[:keyword3]
    keyword4 = project_params[:keyword4]
    start_date = project_params[:start_date]
    end_date = project_params[:end_date]
    financing = project_params[:financing]
    financing_is_public = project_params[:financing_is_public]
    financing_is_nacional = project_params[:financing_is_nacional]
    money_approved = project_params[:money_approved]
    organization = project_params[:organization]
    
    pocketAjeitando = project_params[:pocket].split(';')

    pocket = Array.new(project_params[:numberOfYears].to_i)
    for i in 1..project_params[:numberOfYears].to_i
      pocket[i-1] = pocketAjeitando[i-1].to_f
    end

    if @project.update(coordinator_name: coordinator_name, title: title, subject_area: subject_area, academic_unit: academic_unit, departament: departament, abstract: abstract, keyword1: keyword1, keyword2: keyword2, keyword3: keyword3, keyword4: keyword4, start_date: start_date, end_date: end_date, financing: financing, financing_is_public: financing_is_public, financing_is_nacional: financing_is_nacional, money_approved: money_approved, pocket: pocket, organization: organization)
    
      redirect_to project_path(@project), notice: 'Projeto atualizado com sucesso.'
    else
      redirect_to edit_project_path(@project), notice: 'Não foi possível atualizar o projeto'
    end
  end

  def destroy
    if @project.destroy
      redirect_to admin_index_path, notice: 'Projeto apagado com sucesso.'
    else
      redirect_to @project, notice: 'Não foi possível apagar o projeto'
    end
  end

  # Dynamic select field on form
  def update_departaments
    @departaments = Departament.all.where("Dep_Local = ?", params[:Dep_Local])
    respond_to do |format|
      format.js
    end 
  end

  def update_coordinators
    @coordinators = Coordinator.all.sort_by{|p| p.Ori_Nome}.collect{|p| p.Ori_Nome }
    respond_to do |format|
      format.js
    end 
  end

private
  
  def find_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:coordinator_name, :title, :subject_area, :academic_unit, :departament, :abstract, :keyword1, :keyword2, :keyword3, :keyword4, :start_date, :end_date, :numberOfYears, :financing, :financing_is_public, :financing_is_nacional, :money_approved, :pocket, :codigo, :Dep_Local, :organization)
  end
  


end

app/helpers/projects_helper.rb
module ProjectsHelper

  def coordinator_order
    Coordinator.all.sort_by{|p| p.Ori_Nome}.collect{|p| p.Ori_Nome }
  end

  def place_order
    Place.all.sort_by{|a| a.Loc_Descri}.collect{|a| [a.Loc_Descri, a.Loc_Cod] }
  end

  def conditional_fields(area = nil)
    Departament.all.select {|d| d.Dep_Local == area}
  end

  def find_centro(codigo)
    Place.where(Loc_Cod: codigo).first.Loc_Descri
  end  
end

app/views/projects/_form.html.erb
<%= javascript_include_tag 'form_js_shared' %>
<%= form_for(@project) do |f| %>

    <div class="wrapper-all-form">        
        <div>
            <div>
                <p class="text-center"><%= f.label :coordinator_name, 'Coordenador' %></p>
            </div>
        </div>
        <div class="row coordinator-select">
            <div class="one-column">
                <%= f.select(:coordinator_name, coordinator_order, {include_blank: 'Selecione algo'}, class: 'select2', :id => 'coordinator-select-field')%>
            </div>
        </div>
             
        <hr>
        
        <div class="row">
            <div class="column3-left">
                <%= f.label :academic_unit, 'Centro Acadêmico' %>
            </div>
            
            <div class="column3-mid">
                <%= f.label :departament, 'Departamento' %>
            </div>

            <div class="column3-right">
                <%= f.label :subject_area, 'Área de Estudo'%>
            </div>
            
        </div>
       
        <div class="row">
            <div class="column3-left">
                <%= f.select :academic_unit, options_for_select(@places.collect{|p| [p.Loc_Descri, p.Loc_Cod]}, :selected => f.object.academic_unit), {}, {id: 'academic_unit_select', class: 'select2 select-size'}%>
            </div>

            <div class="column3-mid">
                <%= f.select :departament, options_for_select(@departaments.collect{|d| [d.Dep_descricao, d.Dep_descricao]}, :selected => f.object.departament), {}, {id: 'departaments_select', class: 'select2 select-size'} %>
            </div>

            <div class="column3-right">
                <%= f.select(:subject_area, options_for_select(@areas.collect{|a| [a.Are_Descricao, a.Are_Descricao]}, :selected => f.object.subject_area),{},{class: 'select2 select-size'})%>
            </div>
            
        </div> 

        <hr>
        
        <div class="title-project">
            <%= f.label :title, 'Título' %><br>
            <%= f.text_area :title, size:'70x4', placeholder: 'Digite o título do projeto' %><br>
        </div>
        <div class="abstract-project">
            <%= f.label :abstract, 'Resumo' %><br>
            <%= f.text_area :abstract, class: 'tinymce'%><br>
        </div>

        <div class="keywords">
            <%= f.label :keyword, 'Palavra-chave' %><br>
            | <%= f.text_field :keyword1, placeholder: 'Digite a palavra-chave' %> |
            <%= f.text_field :keyword2, placeholder: 'Digite a palavra-chave' %> |
            <%= f.text_field :keyword3, placeholder: 'Digite a palavra-chave' %> |
            <%= f.text_field :keyword4, placeholder: 'Digite a palavra-chave' %> |
        </div>
        
        <hr>
        <div class="row">
            <div class="column2-left date-select">
                <%= f.label :start_date, 'Início' %><br>
                <%= f.text_field :start_date, :id => 'start_date', placeholder: 'Início' %><br>
            </div>
            
            <div class="column2-right date-select">
                <%= f.label :end_date, 'Fim' %><br>
                <%= f.text_field :end_date, :id => 'end_date', placeholder: 'Fim' %><br>
            </div>
        </div>

        <div class="invisible">
            <%= f.label :numberOfYears%><br>
            <%= f.text_field :numberOfYears, :id => 'numberOfYears' %><br>
        </div>
        
        <hr>
        <div class="financing-area">
            <div class="row">
                <div id="finance" class="center-text">
                    <%= f.label :financing, 'Projeto financiado?' %><br>
                    <%= f.collection_radio_buttons :financing, [[true, 'Sim'], [false, 'Não']], :first, :last do |b| %>
                        <%=b.label { b.radio_button + ' ' + b.text } %><br>
                    <% end %>
                </div>

                <div id="financing-is-public" class="column3-mid invisible">
                    <%= f.label :financing_is_public, 'Financiamento por:'%><br>
                    <%= f.collection_radio_buttons :financing_is_public, [[true, 'Agência de Fomento'], [false, 'Empresa']], :first, :last do |b| %>
                        <%=b.label { b.radio_button + ' ' + b.text } %><br>
                    <% end %>
                </div>

                <div id="financing-is-nacional" class="column3-right invisible">
                    <%= f.label :financing_is_nacional, 'Financiamento:'%><br>
                    <%= f.collection_radio_buttons :financing_is_nacional, [[true, 'Nacional'], [false, 'Internacional']], :first, :last do |b| %>
                        <%=b.label { b.radio_button + ' ' + b.text } %><br>
                    <% end %>
                </div>
            </div>
        </div>
        <div class="organization invisible">
            <p class="text-center"><%= f.label :organization, 'Organização'%></p>
            <p class="text-center"><%= f.select :organization, options_for_select([]), {}, {id: 'agencia-selector', class: 'select2 select-size'}%></p>
        </div>
        <div class="row invisible outro-text-class center-text">
            <%= f.text_field :organization , placeholder: 'Escreva o nome.', :id => 'outro-text-id' %>
        </div>
        <br>
        <div class="one-column">
            <%= f.label :money_approved, 'Recursos Concedidos' %>
            <%= f.text_field :money_approved, :id => 'money_approved', placeholder: 'Digite o valor recebido pelo projeto' %><br>
        </div>
        <br>
        <div class="invisible">
            <%= f.label :pocket, 'Reembolso' %><br>
            <%= f.text_field :pocket, :id => 'pocket', placeholder: 'Digite o valor retirado do seu bolso' %><br>
        </div>

        <%# Nesta div são inseridos campos de reembolso e ao clicar no botão de enviar fomulário, os valores destes campos são colocados no campo da div acima%>
        <div class="reembolso row"></div>


        <%= tinymce %>

        
        <%= f.submit 'Cadastrar', :id => 'form-button'%>
    </div>
<% end %>

app/views/projects/edit.html.erb
<%= render 'form'%>
<div>
  <p class="text-center">
    <% if admin_signed_in? %>
      <%= link_to 'Voltar', admin_index_path, class: 'btn btn-secondary'%>
    <% else %>
      <%= link_to 'Voltar', root_path, class: 'btn btn-secondary'%>
    <% end %>
  </p>
</div>

app/views/projects/index.html.erb
<script type="text/javascript">
  $(function(){
    $(document).ready(function(){
      document.addEventListener("turbolinks:before-cache", function() {
      dataTable.destroy();
    });
    var dataTable = $("#myTable").DataTable({
      columns: [
        { searchable: false},
        { searchable: false},
        null,
        { searchable: false}
      ]
    });
    });
  })
</script>
<div class="wrapper-all-project">
  <div class="project-list">
    <table id="myTable">
      <thead>
        <tr>
          <th>Coordenador</th>
          <th>Título</th>
          <th>Área de estudo</th>
          <th>Vigência</th>
        </tr>
      </thead>
      <tbody>
        <% @projects.each do |project| %>
        <tr>
          <td><%= project.coordinator_name%></td>
          <td><%= link_to project.title, project_path(project) %></td>
          <td><%= project.subject_area%></td>
          <td><%= project.start_date.year%> - <%= project.end_date.year%></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<% if admin_signed_in? %>
  <p class="text-center">
    <%= link_to 'Painel Adminstrativo', admin_index_path, class: 'btn btn-secondary'%>
  </p>
<% end %>

app/views/projects/new.html.erb
<%= render 'form'%>
<div>
  <p class="text-center">
    <%= link_to 'Voltar', root_path, class: 'btn btn-secondary'%>
  </p>
</div>

app/views/projects/show.html.erb
<div class="wrapper-show-project">
  <div class="text-center">
    <div class="">
      <div class="each-field-project">
        <h1>Coordenador</h1>
        <p><%= link_to @project.coordinator.Ori_Nome, @project.coordinator.Ori_EndLattes , target: :_blank %></p>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="column3-left">
      <div class="each-field-project">
        <h1>Centro Acadêmico</h1>
        <p><%= find_centro(@project.academic_unit) %></p>
      </div>
    </div>
    <div class="column3-mid">
      <div class="each-field-project">
        <h1>Departamento</h1>
        <p><%= @project.departament%></p>
      </div>
    </div>
    <div class="column3-right">
      <div class="each-field-project">
        <h1>Área de estudo</h1>
        <p><%= @project.subject_area%></p>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="one-column">
      <div class="each-field-project">
        <h1>Titulo</h1>
        <p><%= @project.title%></p>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="one-column">
      <div class="each-field-project">
        <h1>Resumo</h1>
        <div class="abstract"><p><%= @project.abstract.html_safe%></p></div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="one-column">
      <div class="each-field-project">
        <h1>Palavras-chave</h1>
        <p><%= @project.keyword1%> | 
        <%= @project.keyword2%> | 
        <%= @project.keyword3%> | 
        <%= @project.keyword4%></p>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="column2-left">
      <div class="each-field-project">
        <h1>Início do projeto</h1>
        <p><%= @project.start_date%></p>
      </div>
    </div>
    <div class="column2-left">
      <div class="each-field-project">
        <h1>Fim do projeto</h1>
        <p><%= @project.end_date%></p>
      </div>
    </div>
  </div>
  <% if @project.financing%>
    <div class="row">
      <div class="column3-left">
        <div class="each-field-project">
          <h1>Projeto Financiado</h1>
          <p>Sim</p>
        </div>
      </div>
      <div class="column3-left">
        <div class="each-field-project">
          <h1>Financiamento por:</h1>
          <% if @project.financing_is_public %>
            <p>Agência de Fomento</p>
            <p><b><%= @project.organization %></b></p>
          <% else %>
            <p>Empresa</p>
            <p><b><%= @project.organization %></b></p>
          <% end%>
        </div>
      </div>
      <div class="column3-left">
        <div class="each-field-project">
          <h1>Nacional/Internacional</h1>
          <% if @project.financing_is_nacional %>
            <p>Nacional</p>
          <% else %>
            <p>Internacional</p>
          <% end%>
        </div>
      </div>
    </div>
  <% else %>
    <div class="row">
      <div class="one-column">
        <div class="each-field-project">
          <h1>Projeto Financiado</h1>
          <p>Não</p>
        </div>
      </div>
    </div>
  <% end %>
  <% if admin_signed_in?%>
    <div class="row">
      <div class="one-column">
        <div class="each-field-project">
          <h1>Recursos Concedidos</h1>
          <p><%= number_to_currency(@project.money_approved, unit: "R$", separator:',', delimiter:'.')%></p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="one-column">
        <div class="each-field-project">
          <h1>Reembolso</h1>
          <p>
            <% @project.pocket.each do |value| %>
              <%= number_to_currency(value, unit: 'R$', separator:',', delimiter:'.') %> &nbsp
            <% end %>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="center-text">
  <% if admin_signed_in? %>
    <%= link_to 'Voltar', admin_index_path%> | 
    <%= link_to 'PDF', generate_pdf_path(@project.id), target: :_blank%>
  <% else %>
    <%= link_to 'Voltar', root_path%>
  <% end %>
</div>